// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfFNnJQGopI34V5Dnk1XMGRisCg3t_sU',
    appId: '1:463190675046:web:11bea9c82536900d75a7a7',
    messagingSenderId: '463190675046',
    projectId: 'pet-care-814d9',
    authDomain: 'pet-care-814d9.firebaseapp.com',
    storageBucket: 'pet-care-814d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6MmhCzBbvU7QZZETVgCzrHsfkDBTOgc',
    appId: '1:463190675046:android:3594936f63bf2de675a7a7',
    messagingSenderId: '463190675046',
    projectId: 'pet-care-814d9',
    storageBucket: 'pet-care-814d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeIH7JyY7VG8byy0nomTKZ8sKfblFE6Qo',
    appId: '1:463190675046:ios:596b2251ec5f49f775a7a7',
    messagingSenderId: '463190675046',
    projectId: 'pet-care-814d9',
    storageBucket: 'pet-care-814d9.appspot.com',
    iosClientId: '463190675046-24q2pr4gqhu3mtlah53vie5su7hb4d8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );
}
